const $=s=>document.querySelector(s);let rows=[],fileName='';
function parseCSV(text){const out=[],lines=text.replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean);const headers=splitCSV(lines.shift());for(const line of lines){const vals=splitCSV(line),row={};headers.forEach((h,i)=>row[h.trim()]=vals[i]??'');out.push(row)}return out}
function splitCSV(line){const cells=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){cells.push(cur);cur=''}else cur+=c}cells.push(cur);return cells}
function infer(v){if(v==null||v==='')return'blank';if(!isNaN(Number(v))&&String(v).trim()!=='')return'number';if(!isNaN(Date.parse(v)))return'date';return'category'}
function profileRows(data){const cols=Object.keys(data[0]||{});return cols.map(name=>{const vals=data.map(r=>r[name]).filter(v=>v!==''&&v!=null),types=vals.map(infer),nums=vals.map(Number).filter(Number.isFinite),counts={};vals.forEach(v=>counts[String(v)]=(counts[String(v)]||0)+1);return{name,type:types.filter(t=>t==='number').length/Math.max(vals.length,1)>.8?'number':types.includes('date')?'date':'category',filled:vals.length,missing:data.length-vals.length,unique:Object.keys(counts).length,min:nums.length?Math.min(...nums):null,max:nums.length?Math.max(...nums):null,avg:nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null,top:Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5)}})}
function createBlueprint(profile){const nums=profile.filter(c=>c.type==='number'),cats=profile.filter(c=>c.type==='category'),dates=profile.filter(c=>c.type==='date');return{title:'AI Generated Executive Dashboard',pages:['Executive Overview','Data Quality','Detail Explorer'],kpis:nums.slice(0,4).map(n=>({label:`Total ${n.name}`,measure:`SUM(${n.name})`,field:n.name})),visuals:[dates[0]&&nums[0]?`${nums[0].name} trend by ${dates[0].name}`:null,cats[0]&&nums[0]?`${nums[0].name} by ${cats[0].name}`:null,cats[0]?`${cats[0].name} share`:null].filter(Boolean),narrative:`Detected ${profile.length} fields with ${nums.length} measures, ${cats.length} dimensions, and ${dates.length} date columns.`}}
function generateDax(profile){return profile.filter(c=>c.type==='number').flatMap(c=>[`Total ${c.name} = SUM('Data'[${c.name}])`,`Average ${c.name} = AVERAGE('Data'[${c.name}])`,`Running ${c.name} = CALCULATE([Total ${c.name}], FILTER(ALLSELECTED('Date'[Date]), 'Date'[Date] <= MAX('Date'[Date])))`,`YoY ${c.name} % = DIVIDE([Total ${c.name}] - CALCULATE([Total ${c.name}], SAMEPERIODLASTYEAR('Date'[Date])), CALCULATE([Total ${c.name}], SAMEPERIODLASTYEAR('Date'[Date])))`])}
function groupBy(data,x,y){const m={};data.forEach(r=>{const k=String(r[x]||'Unknown');m[k]=(m[k]||0)+(y?Number(r[y])||0:1)});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([name,value])=>({name,value}))}
function bars(data){const max=Math.max(...data.map(d=>d.value),1);return `<div class="bars">${data.map(d=>`<label>${d.name}<span>${Math.round(d.value).toLocaleString()}</span></label><div><i style="width:${d.value/max*100}%"></i></div>`).join('')}</div>`}
function line(data){const max=Math.max(...data.map(d=>d.value),1),pts=data.map((d,i)=>`${i/(Math.max(data.length-1,1))*100},${100-d.value/max*90}`).join(' ');return `<svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="${pts}"/><g>${data.map((d,i)=>`<circle cx="${i/(Math.max(data.length-1,1))*100}" cy="${100-d.value/max*90}" r="1.4"><title>${d.name}: ${d.value}</title></circle>`).join('')}</g></svg>`}
async function load(file){fileName=file.name;const ext=file.name.split('.').pop().toLowerCase();if(ext==='csv')rows=parseCSV(await file.text());else{if(!window.XLSX){alert('Excel parser is loading from CDN. Try again in a moment or upload CSV.');return}const wb=XLSX.read(await file.arrayBuffer());rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}render('Executive Overview')}
function render(page='Executive Overview'){const profile=profileRows(rows),blueprint=createBlueprint(profile),dax=generateDax(profile),nums=profile.filter(c=>c.type==='number'),cats=profile.filter(c=>c.type==='category'),dates=profile.filter(c=>c.type==='date'),primary=nums[0],cat=cats[0],date=dates[0];$('#app').innerHTML=`<header><div><b>✦</b><h1>AI Dashboard Generator</h1></div><label class="upload">⬆ Upload Excel/CSV<input id="file" type="file" accept=".csv,.xlsx,.xls"></label></header>${!rows.length?`<section class="hero"><h2>Turn spreadsheets into interactive multi-page dashboards.</h2><p>Upload Excel or CSV data to profile fields, generate a dashboard blueprint, create DAX measures, and explore your data in browser-rendered pages.</p></section>`:`<nav>${blueprint.pages.map(p=>`<button data-page="${p}" class="${p===page?'active':''}">${p}</button>`).join('')}<button id="export">Export HTML</button></nav><section class="meta"><b>${fileName}</b><span>${rows.length.toLocaleString()} rows</span><span>${profile.length} columns</span><span>${dax.length} DAX measures</span></section>${page==='Executive Overview'?`<section class="cards">${blueprint.kpis.map(k=>`<article><small>${k.label}</small><strong>${groupBy(rows,k.field).reduce((a,b)=>a+b.value,0).toLocaleString()}</strong><em>${k.measure}</em></article>`).join('')}</section><section class="grid">${date&&primary?panel(`${primary.name} over time`,line(groupBy(rows,date.name,primary.name))):''}${cat&&primary?panel(`${primary.name} by ${cat.name}`,bars(groupBy(rows,cat.name,primary.name))):''}${cat?panel(`${cat.name} share`,bars(groupBy(rows,cat.name))):''}</section>`:''}${page==='Data Quality'?`<section class="grid">${panel('Column profile',table(profile.map(c=>({Column:c.name,Type:c.type,Filled:c.filled,Missing:c.missing,Unique:c.unique}))))}${panel('Completeness score',bars(profile.map(c=>({name:c.name,value:Math.round(c.filled/rows.length*100)}))))}</section>`:''}${page==='Detail Explorer'?`<section class="grid">${panel('Generated DAX',`<pre>${dax.join('\n\n')}</pre>`)}${panel('Dashboard blueprint',`<pre>${JSON.stringify(blueprint,null,2)}</pre>`)}${panel('Data preview',table(rows.slice(0,10)))}</section>`:''}`}`;$('#file').onchange=e=>e.target.files[0]&&load(e.target.files[0]);document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>render(b.dataset.page));$('#export')&&($('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([document.documentElement.outerHTML],{type:'text/html'}));a.download='ai-dashboard.html';a.click()})}
function panel(t,c){return `<article class="panel"><h2>${t}</h2>${c}</article>`}function table(data){const cols=Object.keys(data[0]||{});return `<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${cols.map(c=>`<td>${String(r[c]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
render();
